FROM node:23.11.1-alpine3.21
WORKDIR /usr/src/app
COPY ./address-book-app .
RUN npm install
RUN apk update && apk add nodejs && npm i -g nodemon
EXPOSE 3000
EXPOSE 8080
CMD [ "npm", "run", "start.dev" ]